serve:
  port: 8080

log:
  path: ./logs/

mysql:
  username: root
  password: xinyu..
  host: 101.34.248.67
  port: 3306
  dbname: test
  timeout: 10s

redis:
  addr: 101.34.248.67:6379
  password: xinyu..
  db: 0