serve:
  port: 8080

log:
  path: ./logs/

mysql:
  username: xinyu
  password: xinyu
  host: 127.0.0.1
  port: 3306
  dbname: test
  timeout: 10s

redis:
  addr: 101.34.248.67:6379
  password: xinyu..
  db: 0